import numpy as np
import matplotlib.pyplot as plt
x=np.array([0,1,2,3,4,5,6,7,8,9,10])
y_sin=np.sin(x*36*np.pi/180)
y_f=x**2-10*x+25
fig=plt.figure(figsize=(12,4))
fig.patch.set_facecolor('lightgrey')
plt.subplot(131)
plt.xlabel('x')
plt.ylabel('sin(x)') 
plt.plot(x,y_sin) 
plt.subplot(132)
plt.xlabel('x')
plt.ylabel('f(x)') 
plt.bar(x,y_f) 
plt.subplot(133)
plt.axis('off')
#plt.imshow(img,cmap='gray')
plt.show()
#导入numpy
#导入matplotlib
#创建数组
#计算正弦值
#计算二次函数值
#读取图像
#设置绘图大小
#设置绘图背景
#绘图区域分成1行3列，下面绘制第1个子图
#设置横坐标标题
#设置纵坐标标题
#绘制正弦曲线
#下面绘制第2个子图
#设置横坐标标题
#设置纵坐标标题
#绘制柱状图
#下面绘制第3个子图
#设置不显示坐标轴
#以灰度图显示图片
#显示绘图结果